version: '3'
services:
  functions:
    build:
      context: ./drug-portal-gcp
    command: 
      /bin/sh -c "echo ${GCP_PROJECT_ID}|functions config set projectId ${GCP_PROJECT_ID} && functions config set bindHost 0.0.0.0"
    command:
      /bin/sh -c "functions start && tail -f /dev/null"
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8085
    depends_on:
      - pubsub
    hostname: functions
    ports:
      - 5858:5858
      - 8008:8008
      - 8010:8010
    volumes:
      - gcloudConfig:/root/.config
      - ./drug-portal-cloud-functions:${CONTAINER_WORKING_DIR}
    working_dir: ${CONTAINER_WORKING_DIR} 
  pubsub:
    build: ./drug-portal-gcp
    command: /bin/sh -c "gcloud beta emulators pubsub start --host-port=0.0.0.0:${GCP_PUBSUB_PORT} && tail -f /dev/null"
    hostname: pubsub
    ports:
      - ${GCP_PUBSUB_PORT}:${GCP_PUBSUB_PORT}
    volumes:
      - gcloudConfig:/root/.config
      - ./:${CONTAINER_WORKING_DIR}
    working_dir: ${CONTAINER_WORKING_DIR} 
  gcloud:
    build: ./drug-portal-gcp
    command: gcloud config set project ${GCP_PROJECT_ID}
    volumes:
      - gcloudConfig:/root/.config
      - ./:${CONTAINER_WORKING_DIR}
    working_dir: ${CONTAINER_WORKING_DIR} 
  corb:
    build:
      context: ./drug-portal-marklogic/gradle
      args:
        CORB_JAR_PATH: "${CORB_JAR_PATH}"
    container_name: corb
    image: gradle:ml${ML_VERSION}
    hostname: corb
    volumes:
      - ./:${CONTAINER_WORKING_DIR}
    working_dir: ${CONTAINER_WORKING_DIR} 
  odh:
    build:
      context: drug-portal-marklogic/gradle
      args:
        ODH_INSTALL_PATH: "${ODH_INSTALL_PATH}"
    container_name: odh
    hostname: odh
    image: gradle:ml${ML_VERSION}
    command: "java -jar /opt/odh/${ODH_INSTALL_PATH}"
    ports:
      - "${ODH_PORT}:8080"
    volumes:
      - ./drug-portal-odh/:${CONTAINER_WORKING_DIR}
    working_dir: ${CONTAINER_WORKING_DIR}
  mlcp:
    build:
      context: ./drug-portal-marklogic/gradle
      args:
        CORB_JAR_PATH: "${CORB_JAR_PATH}"
    container_name: mlcp
    image: gradle:ml${ML_VERSION}
    hostname: mlcp
    volumes:
      - ./:${CONTAINER_WORKING_DIR}
    working_dir: ${CONTAINER_WORKING_DIR} 
  marklogic:
    build:
      context: ./drug-portal-marklogic/marklogic
      args:
        ML_INSTALL_PATH: "${ML_INSTALL_PATH}"
        ML_CONVERTERS_PATH: "${ML_CONVERTERS_PATH}"
    image: "marklogic:marklogic${ML_VERSION}"
    container_name: "marklogic"
    hostname: marklogic
    volumes:
      - "./${LOCAL_VOLUME_DIR}/marklogic${ML_VERSION}-${BUILD_ENV}-1:/var/opt/MarkLogic"
    ports:
      - "${ML_PORT_LOWER}-${ML_PORT_UPPER}:${ML_PORT_LOWER}-${ML_PORT_UPPER}"
      - 8040-8050:8040-8050
    command: /bin/sh -c "/etc/init.d/MarkLogic start && tail -f /dev/null"
  slush:
    build:
      context: drug-portal-marklogic/slush
    container_name: slush
    hostname: slush
    image: ruby-node
    ports:
      - 3000:3000
      - 9070:9070
      - 8030:8030
    volumes:
      - ./drug-portal-slush-app/:${CONTAINER_WORKING_DIR}
    working_dir: ${CONTAINER_WORKING_DIR}
    command: /bin/sh -c "gulp serve-local && tail -f /dev/null"
volumes:
  gcloudConfig:
